version: "3.8"
services:
  db:
    image: mysql:8.0.30
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: db_user
      MYSQL_PASSWORD: db_user_pass
      MYSQL_DATABASE: db_TechSolutions
    restart: always
    ports:
      - "6033:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin:5.2.0
    container_name: pma_container
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - "8081:80"
    networks:
      - app-network
    depends_on:
      - db

  app:
    build:
      context: .
      dockerfile: nodejs.dockerfile
    container_name: node_app
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=development
      - DB_HOST=db
      - DB_USER=db_user
      - DB_PASSWORD=db_user_pass
      - DB_NAME=db_TechSolutions
      - DB_PORT=3306
    volumes:
      - ./app:/home/node/app
      - ./ssl:/home/node/app/ssl
      - /home/node/app/node_modules
    ports:
      - "443:443"
    command: "npm start"
    networks:
      - app-network
    depends_on:
      - db

volumes:
  dbdata:

networks:
  app-network:
    driver: bridge
